version: "3.7"

networks:
  dockerapi-dev:
    driver: bridge

services:
  dockerapi:
    image: dockerapi:latest
    depends_on:
      - 'postgres_image'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
      - '5000:5000'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION_STRING: 'host=postgres_image;port=5432;database=releasenotedb;username=dbuser;password=dbpassword;'
    networks:
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - '5432'
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'dbuser'
      POSTGRES_PASSWORD: 'dbpassword'
      POSTGRES_DB: 'releasenotedb'
    networks:
      - dockerapi-dev
        
  webapp:
    image: webapp:latest
    build:
      context: ../ReleaseNotes-WebApp/
      dockerfile: Dockerfile
    ports:
    - '3000:3000'
    command:
      npm start
    volumes:
    - ../ReleaseNotes-WebApp/:/usr/src/app

volumes:
  db_volume: