version: "3.7"

networks:
  dockerapi-dev:
    driver: bridge

services:
  dockerapi:
    image: dockerapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=releasenotedb;username=dbuser;password=dbpassword;"
    networks:
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
      POSTGRES_DB: "releasenotedb"
    networks:
      - dockerapi-dev
    
  test-runner:
    image: test-runner
    build:
      context: ./TestContainer/
      dockerfile: Dockerfile
    command: dockerize
      -wait tcp://dockerapi:5000 -timeout 10s
      bash -c "yarn test --file test/testAuth.js"
    environment:
      APP_URL: http://dockerapi:5000
    depends_on:
      - dockerapi
    networks:
      - dockerapi-dev